-- Clear existing menu items first
DELETE FROM menu_items;

-- Lunch Menu Items
INSERT INTO menu_items (name, description, price, category, meal_type, available_settings, available) VALUES 
('Rainbow Mesclun', 'Assorted Greens, Tomatoes, Cucumbers, Shredded Carrots & Choice of Dressing', 12.00, 'Salads', 'lunch', 'House-Made Balsamic; Champagne; Honey Mustard; Blue Cheese; Thousand Island; Ranch; EVOO & Balsamic Vinegar', true),
('Classic Caesar', 'Romaine, Parmesan, Croutons & Caesar Dressing', 12.00, 'Salads', 'lunch', '', true),
('Quinoa', 'Baby Arugula, Cherry Tomatoes, Sweet Red Onions, Corn, Avocado & Sherry Vinaigrette', 16.00, 'Salads', 'lunch', '', true),
('Queen', 'Assorted Greens, Dried Cranberries, Fresh Strawberries, Blackberries, Orange Segments, Candied Walnuts & Champagne Vinaigrette', 16.00, 'Salads', 'lunch', '', true),
('Bam-Bam Shrimp Wrap', 'Mixed Greens & Tomatoes', 18.00, 'Chef Specialties', 'lunch', '', true),
('Brisket Sandwich', 'Braised Brisket, Melted Provolone & Fried Onions on Ciabatta', 21.00, 'Chef Specialties', 'lunch', '', true),
('12 Cheese Pizza', 'Cheese pizza (12") – toppings $1.50 each: Mushrooms; Pepperoni; Peppers; Onions', 14.00, 'Chef Specialties', 'lunch', 'Mushrooms; Pepperoni; Peppers; Onions', true),
('10 oz Angus Burger', 'Served with Lettuce, Tomato & Red Onion on Brioche', 18.00, 'Packanacks Picks', 'lunch', 'Bacon; Sautéed Onions; American; Cheddar; Swiss Cheese', true),
('Veggie Burger', 'Served with Lettuce, Tomato & Red Onion on Brioche', 14.50, 'Packanacks Picks', 'lunch', 'Sautéed Onions; American; Cheddar; Swiss Cheese; Blue Cheese', true),
('Thummans All Beef Hot Dog', 'Served with Sauerkraut', 8.00, 'Packanacks Picks', 'lunch', 'Sauerkraut', true),
('Chicken Wings (7)', 'Served with Celery & choice of Blue Cheese or Cool Ranch', 12.00, 'Packanacks Picks', 'lunch', 'Buffalo; BBQ; Sweet Thai Chili; Cajun', true),
('Chicken Wings (16)', 'Served with Celery & choice of Blue Cheese or Cool Ranch', 23.00, 'Packanacks Picks', 'lunch', 'Buffalo; BBQ; Sweet Thai Chili; Cajun', true),
('Chicken Quesadilla', 'Served with Salsa & Sour Cream', 14.00, 'Packanacks Picks', 'lunch', 'Salsa; Sour Cream', true),
('Happy Waitress', 'Grilled Cheese with Tomato & Crispy Bacon', 14.00, 'Packanacks Picks', 'lunch', '', true),
('French Fries', 'French Fries', 4.75, 'Sides', 'lunch', '', true),
('French Fries with Cheese', 'French Fries with Cheese', 6.00, 'Sides', 'lunch', '', true),
('French Fries with Cheese & Bacon', 'French Fries with Cheese & Bacon', 8.50, 'Sides', 'lunch', '', true),
('Beer Battered Onion Rings', 'Beer Battered Onion Rings', 7.00, 'Sides', 'lunch', '', true),
('BLTA', 'Crispy Bacon, Lettuce, Tomato & Avocado on choice of bread', 14.00, 'Sandwiches', 'lunch', 'French Fries; Cole Slaw; Fresh Fruit Salad', true),
('Turkey Sloppy Joe', 'Turkey Breast, Swiss Cheese, Cole Slaw & Russian Dressing on Rye', 16.00, 'Sandwiches', 'lunch', 'French Fries; Cole Slaw; Fresh Fruit Salad', true),
('Turkey Club', 'Turkey Breast, Swiss Cheese, Bacon, Avocado, Lettuce & Tomato on White Toast', 17.00, 'Sandwiches', 'lunch', 'French Fries; Cole Slaw; Fresh Fruit Salad', true),
('Fried Chicken Sandwich', 'Crispy Chicken, Lettuce, Pickles, Pickled Radish & Chipotle Aioli on a Butter Roll', 15.50, 'Sandwiches', 'lunch', 'French Fries; Cole Slaw; Fresh Fruit Salad', true),
('Grilled Chicken Club', 'Marinated Chicken, Bacon, Lettuce, Tomato & Mayo on Ciabatta', 16.75, 'Sandwiches', 'lunch', 'French Fries; Cole Slaw; Fresh Fruit Salad', true),
('Crabcake Sandwich', 'Rainbow Greens, Avocado, Bacon & Tartar Sauce on Brioche', 18.00, 'Sandwiches', 'lunch', 'French Fries; Cole Slaw; Fresh Fruit Salad', true),
('The Godfather', 'Chicken Cutlet, Broccoli Rabe & Melted Provolone on French Loaf', 18.00, 'Sandwiches', 'lunch', 'French Fries; Cole Slaw; Fresh Fruit Salad', true),
('Ribeye Steak Sandwich', 'Diced Peppers, Onions, Mushrooms, Melted Provolone & Au Jus on French Loaf', 21.00, 'Sandwiches', 'lunch', 'French Fries; Cole Slaw; Fresh Fruit Salad', true),
('Tuna Salad BLT', 'Tuna Salad, Bacon, Lettuce & Tomato', 16.00, 'Wraps', 'lunch', 'French Fries; Cole Slaw; Fresh Fruit Salad', true),
('Buffalo Chicken', 'Chicken Fingers, Lettuce, Tomato, Red Onion, Blue Cheese & Buffalo Sauce', 15.50, 'Wraps', 'lunch', 'French Fries; Cole Slaw; Fresh Fruit Salad', true),
('Grilled Chicken Caesar', 'Grilled Chicken, Parmesan Cheese & Caesar Dressing', 15.00, 'Wraps', 'lunch', 'French Fries; Cole Slaw; Fresh Fruit Salad', true),
('Grilled Chicken Waldorf', 'Grilled Chicken, Apple, Grapes & Walnuts', 16.00, 'Wraps', 'lunch', 'French Fries; Cole Slaw; Fresh Fruit Salad', true),
('Cheezy Western Omelet', '(3) Eggs, Diced Peppers, Onions, Mushrooms, Ham, Cheese, Fries & Toast', 14.00, 'Breakfast Corner', 'lunch', '', true),
('Taylor Ham, Egg & Cheese', 'Taylor Ham, Egg & Cheese', 10.00, 'Breakfast Corner', 'lunch', '', true),
('Bacon, Egg & Cheese', 'Bacon, Egg & Cheese', 10.00, 'Breakfast Corner', 'lunch', '', true);

-- Dinner Menu Items
INSERT INTO menu_items (name, description, price, category, meal_type, available_settings, available) VALUES 
('Shrimp In White Wine Garlic Sauce', 'Served with Grilled Bread', 15.00, 'Starters', 'dinner', '', true),
('Spinach & Artichoke Dip', 'Served with Tortilla Chips', 13.00, 'Starters', 'dinner', '', true),
('Chicken Lemongrass Dumplings', 'Steamed or Fried, served with Ponzu Scallion Sauce', 10.00, 'Starters', 'dinner', '', true),
('Bam-Bam Shrimp', 'Crispy Shrimp in a Creamy Sweet Chili Sauce', 18.00, 'Starters', 'dinner', '', true),
('Fried Calamari', 'Served with Marinara & Lemon Wedges', 14.00, 'Starters', 'dinner', '', true),
('House Salad', 'Fresh Garden Greens, Tomatoes, Cucumbers & Carrots with choice of dressing', 6.50, 'Salads', 'dinner', 'Dressings: House-Made Balsamic Vinaigrette; Champagne Vinaigrette; Honey Mustard; Blue Cheese; Thousand Island; Ranch; EVOO & Balsamic Vinegar; Enhancements: Grilled Chicken $6; Grilled Steak $15; Crabcake $9.50; Grilled Shrimp $10; Grilled Salmon $9.50', true),
('House Salad (Large)', 'Fresh Garden Greens, Tomatoes, Cucumbers & Carrots with choice of dressing', 12.00, 'Salads', 'dinner', 'Dressings: House-Made Balsamic Vinaigrette; Champagne Vinaigrette; Honey Mustard; Blue Cheese; Thousand Island; Ranch; EVOO & Balsamic Vinegar; Enhancements: Grilled Chicken $6; Grilled Steak $15; Crabcake $9.50; Grilled Shrimp $10; Grilled Salmon $9.50', true),
('Classic Caesar Salad', 'Crisp hearts of Romaine, homemade croutons & Parmesan cheese', 6.50, 'Salads', 'dinner', 'Dressings: Caesar; Enhancements: Grilled Chicken $6; Grilled Steak $15; Crabcake $9.50; Grilled Shrimp $10; Grilled Salmon $9.50', true),
('Classic Caesar Salad (Large)', 'Crisp hearts of Romaine, homemade croutons & Parmesan cheese', 12.00, 'Salads', 'dinner', 'Dressings: Caesar; Enhancements: Grilled Chicken $6; Grilled Steak $15; Crabcake $9.50; Grilled Shrimp $10; Grilled Salmon $9.50', true),
('Packanack Salad', 'Mesclun greens, fresh strawberries, mango, goat cheese, walnuts & sun-dried cranberries with Champagne vinaigrette', 16.50, 'Salads', 'dinner', 'Enhancements: Grilled Chicken $6; Grilled Steak $15; Crabcake $9.50; Grilled Shrimp $10; Grilled Salmon $9.50', true),
('French Onion Soup', '', 7.00, 'Soups', 'dinner', '', true),
('Chili All The Way Soup', '', 7.00, 'Soups', 'dinner', '', true),
('Soup Du Jour', '', 7.00, 'Soups', 'dinner', '', true),
('Farfalle with Italian Sausage & Broccoli Rabe', 'Pecorino cheese & grilled bread', 14.00, 'Pastas', 'dinner', '', true),
('Four Cheese Ravioli', 'In a creamy pesto sauce', 20.00, 'Pastas', 'dinner', '', true),
('PGC Penne Vodka', 'Mushrooms, onions, English peas & sun-dried tomatoes tossed in vodka sauce', 19.00, 'Pastas', 'dinner', 'Enhancements: Grilled Chicken $6; Salmon $9.50; Grilled Shrimp $10', true),
('Seared Salmon', 'With chunky avocado/mango salsa; served with sautéed garden vegetables over basmati rice', 28.00, 'Entrees – Seafood', 'dinner', '', true),
('Pan Seared Bronzino', 'With Mediterranean herbs; served with mashed potatoes, broccolini, pearl onions & carrots', 33.00, 'Entrees – Seafood', 'dinner', '', true),
('Filet Mignon', 'Grilled asparagus, mushrooms & mashed potatoes', 41.00, 'Entrees – Meat', 'dinner', 'Preparation: Simply Grilled; Blackened; Gorgonzola Crusted; Maître Dhôtel Butter', true),
('Rosemary & Garlic Flat Iron Steak', 'Haricot verts, squash, zucchini, onions & mashed potatoes', 33.00, 'Entrees – Meat', 'dinner', '', true),
('Saltimbocca', 'Topped with spinach, prosciutto, provolone & mushroom sauce; served with choice of pasta', 26.00, 'Entrees – Chicken', 'dinner', 'Choice of Pasta', true),
('Parmesan/Marsala/Française Chicken', 'Served with choice of pasta', 22.00, 'Entrees – Chicken', 'dinner', 'Preparation: Parmesan; Marsala; Française; Choice of Pasta', true),
('10 oz Black Angus Burger', 'Served with French fries', 18.00, 'Casual', 'dinner', 'Add-ons: Bacon; Sautéed Onions; Sautéed Mushrooms; American Cheese; Swiss Cheese; Cheddar Cheese; Blue Cheese', true),
('Grilled Chicken Sandwich', 'Grilled chicken, eggplant, grilled red peppers, bacon & provolone cheese on brioche; served with French fries', 16.50, 'Casual', 'dinner', '', true),
('Crabcake Sandwich Dinner', 'Mixed greens, avocado, bacon & tartar sauce; served with French fries', 18.00, 'Casual', 'dinner', '', true),
('Club Sandwich', 'Turkey, bacon, Swiss cheese, avocado, lettuce, tomato & mayo on white toast; served with French fries', 17.00, 'Casual', 'dinner', '', true),
('Tacos', 'Cumin-baked choice of meat with lettuce, tomato, lime mayo aioli & cole slaw; served on corn or flour tortilla', 15.00, 'Casual', 'dinner', 'Meat: Chicken $15; St. Peters Fish $15; Shrimp $19; Steak $23; Tortillas: Corn; Flour', true);